name: FastAPI Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build . --file Dockerfile --tag zach27/github_actions:API
        docker images -a
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        ecr: auto
        logout: true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Publish the Docker Image
      run: |
        docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push zach27/github_actions:API

    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1
